// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace backend.Migrations.AggregateDb
{
    [DbContext(typeof(AggregateDbContext))]
    [Migration("20260929210657_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.AveragePer8HourShift", b =>
                {
                    b.Property<Guid>("SampleId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExposureType")
                        .HasColumnType("text");

                    b.Property<TimeSpan>("AverageTimeInSafeLimits")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("AverageTimeOverAction")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("AverageTimeOverLimit")
                        .HasColumnType("interval");

                    b.HasKey("SampleId", "ExposureType");

                    b.ToTable("AveragePer8HourShift", (string)null);
                });

            modelBuilder.Entity("Backend.Models.DustAverage", b =>
                {
                    b.Property<Guid>("SampleId")
                        .HasColumnType("uuid");

                    b.Property<double>("AveragePm10Stel")
                        .HasColumnType("double precision");

                    b.Property<double>("AveragePm10Twa")
                        .HasColumnType("double precision");

                    b.Property<double>("AveragePm1Stel")
                        .HasColumnType("double precision");

                    b.Property<double>("AveragePm1Twa")
                        .HasColumnType("double precision");

                    b.Property<double>("AveragePm25Stel")
                        .HasColumnType("double precision");

                    b.Property<double>("AveragePm25Twa")
                        .HasColumnType("double precision");

                    b.Property<double>("AveragePm4Stel")
                        .HasColumnType("double precision");

                    b.Property<double>("AveragePm4Twa")
                        .HasColumnType("double precision");

                    b.HasKey("SampleId");

                    b.ToTable("DustAverage", (string)null);
                });

            modelBuilder.Entity("Backend.Models.NoiseAverage", b =>
                {
                    b.Property<Guid>("SampleId")
                        .HasColumnType("uuid");

                    b.Property<double>("AverageLaeq")
                        .HasColumnType("double precision");

                    b.Property<double>("AverageLcpk")
                        .HasColumnType("double precision");

                    b.HasKey("SampleId");

                    b.ToTable("NoiseAverage", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Sample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("SampleCount")
                        .HasColumnType("integer");

                    b.Property<string>("SampleQualifier")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SampleType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Sample", null, t =>
                        {
                            t.HasCheckConstraint("CK_Sample_SampleCount_Nonnegative", "\"SampleCount\" >= 0");
                        });
                });

            modelBuilder.Entity("Backend.Models.VibrationAverage", b =>
                {
                    b.Property<Guid>("SampleId")
                        .HasColumnType("uuid");

                    b.Property<double>("AverageExposure")
                        .HasColumnType("double precision");

                    b.HasKey("SampleId");

                    b.ToTable("VibrationAverage", (string)null);
                });

            modelBuilder.Entity("Backend.Models.AveragePer8HourShift", b =>
                {
                    b.HasOne("Backend.Models.Sample", "Sample")
                        .WithMany("AveragesPer8HourShift")
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sample");
                });

            modelBuilder.Entity("Backend.Models.DustAverage", b =>
                {
                    b.HasOne("Backend.Models.Sample", "Sample")
                        .WithOne("DustAverage")
                        .HasForeignKey("Backend.Models.DustAverage", "SampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sample");
                });

            modelBuilder.Entity("Backend.Models.NoiseAverage", b =>
                {
                    b.HasOne("Backend.Models.Sample", "Sample")
                        .WithOne("NoiseAverage")
                        .HasForeignKey("Backend.Models.NoiseAverage", "SampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sample");
                });

            modelBuilder.Entity("Backend.Models.VibrationAverage", b =>
                {
                    b.HasOne("Backend.Models.Sample", "Sample")
                        .WithOne("VibrationAverage")
                        .HasForeignKey("Backend.Models.VibrationAverage", "SampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sample");
                });

            modelBuilder.Entity("Backend.Models.Sample", b =>
                {
                    b.Navigation("AveragesPer8HourShift");

                    b.Navigation("DustAverage");

                    b.Navigation("NoiseAverage");

                    b.Navigation("VibrationAverage");
                });
#pragma warning restore 612, 618
        }
    }
}
