// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251016111952_NoteTable")]
    partial class NoteTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.NoteData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("NoteData");
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("Backend.Records.DustData", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("PM10S")
                        .HasColumnType("double precision");

                    b.Property<double>("PM10T")
                        .HasColumnType("double precision");

                    b.Property<double>("PM1S")
                        .HasColumnType("double precision");

                    b.Property<double>("PM1T")
                        .HasColumnType("double precision");

                    b.Property<double>("PM25S")
                        .HasColumnType("double precision");

                    b.Property<double>("PM25T")
                        .HasColumnType("double precision");

                    b.Property<double>("PM4S")
                        .HasColumnType("double precision");

                    b.Property<double>("PM4T")
                        .HasColumnType("double precision");

                    b.HasKey("Id", "Time");

                    b.ToTable("DustData");
                });

            modelBuilder.Entity("Backend.Records.NoiseData", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("LavgQ3")
                        .HasColumnType("double precision");

                    b.HasKey("Id", "Time");

                    b.ToTable("NoiseData");
                });

            modelBuilder.Entity("Backend.Records.VibrationData", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ConnectedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DisconnectedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Exposure")
                        .HasColumnType("double precision");

                    b.HasKey("Id", "ConnectedOn");

                    b.ToTable("VibrationData");
                });
#pragma warning restore 612, 618
        }
    }
}
